files:
  include: '**/*.s+(a|c)ss'
rules:
  border-zero: 1
  brace-style: 0
  empty-line-between-blocks:
    - 1
    -
      allow-single-line-rulesets: false
  extends-before-declarations: 0
  extends-before-mixins: 2
  final-newline:
    - 0
    -
      include: false
  hex-length: 1
  hex-notation: 2
  indentation: 0
  leading-zero:
    - 2
    -
      include: true
  mixins-before-declarations:
    - 2
    -
      excludes: [ 'respond-to' ]
  nesting-depth: 2
  no-color-keywords: 0
  no-color-literals:
    - 2
    -
      allow-rgba: true
  no-duplicate-properties: 1
  no-empty-rulesets: 2
  no-extends: 1
  no-ids: 2
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 1
  no-misspelled-properties: 2
  no-qualifying-elements: 2
  no-trailing-zero: 2
  no-url-protocols: 2
  no-vendor-prefixes: 2
  one-declaration-per-line: 2
  property-sort-order:
    - 2
    -
      order: 'alphabetical'
  quotes: 2
  shorthand-values: 1
  single-line-per-selector: 0
  space-after-colon: 2
  space-after-comma: 2
  space-before-bang: 2
  space-before-colon: 2
  space-between-parens: 2
  url-quotes: 1
  variable-name-format:
    - 2
    -
      convention: ^[^_]*
  zero-unit: 1
